### PR TITLE
Tests! (and the refactor that enables them)

### PR DESCRIPTION
**Pull request by zmc**
More to come later :)

### CODE REVIEW

**Comment by zmc** [comment]
To run tests:
```
virtualenv -p python3 virtualenv
pip3 install -r requirements.txt
source ./virtualenv/bin/activate
py.test -v nsupdate_web
```

**Comment by sorz** [comment]
I just send you the collaborator invite.
You may push directly.

**Comment by zmc** [comment]
Thank you @sorz! Would you like me to continue filing pull requests or should I just push (tested) commits to `master`?

**Comment by sorz** [comment]
Just push to `master`, thanks. 😄

**Pull request merged**
